# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 67e809f2d0828fdfa13fa08f76f62c63426496b589c5991832ca5499f7a45807516731f9894bcda3981e6adda2e9615b5b7c1efe8a2f84bf2aa44716294070ae

test:
  secret_key_base: db7255ffb70e394cad24cace38fed182e46aa5bf28c3f53a01948c9fa0ecee6942cd2fddf143034de4d770152d086ef625bc54d8e873bda52abdf96eb7d96524

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
